//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.UserControls {


    public partial class NewsForm
    {
        protected global::Microsoft.SharePoint.WebControls.FieldLabel lblTitle;
        protected global::Microsoft.SharePoint.WebControls.TextField txtTitle;
        protected global::Microsoft.SharePoint.WebControls.SaveButton saveButton;
        protected global::Microsoft.SharePoint.WebControls.GoBackButton goBackButton;
        protected global::Microsoft.SharePoint.WebControls.SaveButton saveButton1;
        protected global::Microsoft.SharePoint.WebControls.GoBackButton goBackButton1;
    }
}
