//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class LeftNewsContentUS
    {
        /// <summary>
        /// rptLatestNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptCaiCachThuTucHanhChinh;

        protected global::System.Web.UI.WebControls.Label lblHeader;
        protected global::System.Web.UI.WebControls.Label lblShortContent;
        protected global::System.Web.UI.WebControls.Repeater rptNewsGroup;
        protected global::System.Web.UI.WebControls.LinkButton lbRSS;
        protected global::System.Web.UI.WebControls.Image imgThumb;
        protected global::System.Web.UI.WebControls.Literal ltrImage;
    }
}
