//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class DocumentsManagerUS
    {
        protected global::System.Web.UI.WebControls.Label lblFocusCompany;
        protected global::System.Web.UI.WebControls.Repeater rptFocusCompany;
        //protected global::System.Web.UI.WebControls.Image img;
        protected global::System.Web.UI.WebControls.Literal ltrFlash1;
    }
}
