//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class NewsDetailUS
    {
        protected global::System.Web.UI.WebControls.Literal ltrNewsContent;
        protected global::System.Web.UI.WebControls.Label lblCurrentDate;
        protected global::System.Web.UI.WebControls.Label lblBreadCrum;

        protected global::System.Web.UI.WebControls.Panel pnlAttachment;

        protected global::System.Web.UI.WebControls.Repeater rptAttachment;
        protected global::System.Web.UI.WebControls.Label lblAttachFiles;
    }
}
