//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class NewsListUS
    {
        protected global::System.Web.UI.WebControls.Repeater rptListCategory;
        protected global::System.Web.UI.WebControls.Label lblItemNotExist;
        protected global::System.Web.UI.WebControls.Label  lblCurrpage;
        protected global::System.Web.UI.WebControls.HyperLink lnkPrev;
        protected global::System.Web.UI.WebControls.HyperLink lnkNext;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Panel pnlCategory;
        protected global::System.Web.UI.WebControls.Repeater rptCaregory;
        protected global::System.Web.UI.WebControls.Label lblCategoryTitle;
    }
}
