//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class HotNewsContentUS
    {
        protected global::System.Web.UI.WebControls.Repeater rptLatestNews;
        protected global::System.Web.UI.WebControls.Repeater rptTopViews;
        protected global::System.Web.UI.WebControls.Repeater rptImages;
        protected global::System.Web.UI.WebControls.Label lblShortContent;

        protected global::System.Web.UI.WebControls.Label lblTimeUpdate;

        protected global::System.Web.UI.WebControls.Image imgMainImage;

        protected global::System.Web.UI.WebControls.Panel pnlIndex;

        protected global::System.Web.UI.WebControls.Panel pnlSubPage;

        protected global::System.Web.UI.WebControls.Repeater rptThreeItem;

        protected global::System.Web.UI.WebControls.Label lblLate;
    }
}
