//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class ClassiFiedsUS
    {
        protected global::System.Web.UI.WebControls.Repeater rptFocusCompany;
        protected global::System.Web.UI.WebControls.LinkButton lbtImage;
        protected global::System.Web.UI.WebControls.Image img;
    }
}
