//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class NextNewsUS
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlDays;
        protected global::System.Web.UI.WebControls.DropDownList ddlMonths;
        protected global::System.Web.UI.WebControls.DropDownList ddlYears;
        protected global::System.Web.UI.WebControls.LinkButton lnkNextNews;
    }
}
