//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class NewsDetailUS
    {
        protected global::System.Web.UI.WebControls.Literal ltrNewsContent;

        protected global::System.Web.UI.WebControls.Label lblBreadCrum;

        protected global::System.Web.UI.WebControls.Panel pnlAttachment;

        protected global::System.Web.UI.WebControls.Repeater rptAttachment;
        protected global::System.Web.UI.WebControls.Label lblAttachFiles;
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.Literal ltrShortDescription;
        protected global::System.Web.UI.WebControls.Label lblCreatedDate;
        protected global::System.Web.UI.WebControls.Panel pnlNewsDetail;
        protected global::System.Web.UI.WebControls.Panel pnlChuyenDe;
        protected global::System.Web.UI.WebControls.Repeater rptChuyenDe;

        protected global::System.Web.UI.WebControls.Label lblAuthor;
        protected global::System.Web.UI.WebControls.Label lblSource;
        protected global::System.Web.UI.WebControls.Label lblItemDoesNotExist;
        protected global::System.Web.UI.WebControls.Literal ltrPublishingPageImage;
        protected global::System.Web.UI.WebControls.Literal ltrCommentForImage;
        protected global::System.Web.UI.WebControls.Label lblCurrpage;
        protected global::System.Web.UI.WebControls.HyperLink lnkPrev;
        protected global::System.Web.UI.WebControls.HyperLink lnkNext;

        protected global::System.Web.UI.WebControls.Panel pnlCauHinhChuyenDe;
        protected global::System.Web.UI.WebControls.Repeater rptCauHinhChuyenDe;
        protected global::System.Web.UI.WebControls.DropDownList ddlSelectOrder;
        protected global::System.Web.UI.WebControls.Button btnSaveData;
        protected global::System.Web.UI.WebControls.Label lblId;
        protected global::System.Web.UI.WebControls.Label lblTitle1;
    }
}
