//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class ModeNewsContentUS
    {
        /// <summary>
        /// rptLatestNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptTinhUy;

        /// <summary>
        /// rptLatestNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptHoiDongNhanDan;

        /// <summary>
        /// rptLatestNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptUyBanNhanDan;
        protected global::System.Web.UI.WebControls.Label lblHeaderTinhUy;
        protected global::System.Web.UI.WebControls.Label lblHeaderHoiDongNhanDan;
        protected global::System.Web.UI.WebControls.Label lblHeaderUyBanNhanDan;

        protected global::System.Web.UI.WebControls.Label lblFirstGroup;
        protected global::System.Web.UI.WebControls.Label lblSecondGroup;
        protected global::System.Web.UI.WebControls.Label lblThirdGroup;
        protected global::System.Web.UI.WebControls.Image img1;
        protected global::System.Web.UI.WebControls.Image Img2;
        protected global::System.Web.UI.WebControls.Image Img3;
    }
}
