//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class FocusNewsUS
    {
        protected global::System.Web.UI.WebControls.Repeater rptFocusNews;

        //protected global::System.Web.UI.WebControls.Label lblDate;
        protected global::System.Web.UI.WebControls.Label lblSeeMore;
        protected global::System.Web.UI.WebControls.Literal ltrImage;
    }
}
