//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CQ.SharePoint.QN.Webparts
{
    public partial class AllDocumentsUS
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlChuyenDe;
        protected global::System.Web.UI.WebControls.DropDownList ddlLoaiVanBan;
        protected global::System.Web.UI.WebControls.TextBox txtTrichYeu;
        protected global::System.Web.UI.WebControls.DropDownList ddlNamBanHanh;
        protected global::System.Web.UI.WebControls.TextBox txtKyHieuVanBan;
        protected global::System.Web.UI.WebControls.TextBox txtTuNgay;
        protected global::System.Web.UI.WebControls.TextBox txtDenNgay;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnRefresh;
        protected global::System.Web.UI.WebControls.DataList dlPaginationSample;
        protected global::System.Web.UI.WebControls.Panel pnlPager;
    }
}
